apiVersion: v1
kind: Pod
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  containers:
    - name: debugger
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - bin/bash
        - '-c'
        - sleep 3600  